LOCAL_MODULE    := c
LOCAL_SRC_FILES := .c

WINDOW_FEATURE:=FLAG_FULLSCREEN
SCREEN:=SCREEN_ORIENTATION_LANDSCAPE
versionName:=1
versionCode:=1.01
LOCAL_SRC_FILES:=main.c
PACKAGE:=com.xx
APP_NAME:=这是个游戏
TITLE:=这是个游戏