LOCAL_MODULE    := c
LOCAL_SRC_FILES := mynes.c

APP_NAME:=nes模拟器
LOAD_C_FILES_DIR := src
PACKAGE:=com.xl.opnesroid
#SCREEN:=SCREEN_ORIENTATION_LANDSCAPE
WINDOW_FEATURE:=FLAG_FULLSCREEN
versionName:=1.2
RUN_MODE:=so